name: Hosted App Integration

on:
  push:
    branches:
      - main

jobs:
  hosted-app:
    name: Use Hosted App Link
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Use Hosted App Link
    - name: Use Hosted App
      run: echo "Hosted App is available at: https://studio--engiexplain.us-central1.hosted.app/"
